stages:
  - build
  - test

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits-signoffs.yml'
  - remote: 'https://raw.githubusercontent.com/mendersoftware/mendertesting/7359b0be7b7a20a23d8c91ee7bfc32c54c915b6b/.gitlab-ci-template-k8s-test.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'

build:
  stage: build
  image: debian:buster
  before_script:
    - apt-get update -y
    - apt-get install -y curl make
    - curl -L https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  script:
    - make lint
    - make package
  artifacts:
    expire_in: 2w
    paths:
      - mender-*.tgz

test_helm_chart_install:
  extends: .test_on_k8s_cluster
  variables:
    K8S_VERSION: "v1.18.15"
    KIND_VERSION: "v0.10.0"
  dependencies:
    - build
  script:
    - tests/ci-deps-k8s.sh
    - tests/ci-make-helm.sh
    - make test
